@startuml Indie_Studio
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

namespace Client {
     class Test<T> {

        -T _x;
        -T _y;
    }

}

namespace Sound {
    class ISoundManager {
        +int recordAudio() = 0;
        +int playAudio() = 0;
        +bool isStreamActive() = 0;
    }

    class ASoundManager {
        -std::array<float> _sample;
    }
}

namespace SoundLib {
    class PortAudioManager {}
}

Sound.ISoundManager->Sound.ASoundManager
Sound.ASoundManager->SoundLib.PortAudioManager
@enduml