@startuml Babel
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

namespace Client {
     class Test<T> {

        -T _x;
        -T _y;
    }

}

namespace Load {
    class DLLoader<T> {
        +static std::shared_ptr<T> getEntryPoint(std::string filePath);
    }

    class ConfigFileParser {}
}

namespace Sound {
    class EncodedSound {
        -unsigned char *buffer;
        -int size;
    }

    class CircularBuffer {
        -void *buf;
        -int _length;
        -int tail;
        -int head;

        +void cleanup();
        +void clear();
        +void *getHead() const;
        +void *getTail() const;
        +void freeBytes(int amount);
        +void allocateBytes(int amount);
        +int writeToBuffer(const void *src, int len);
    }

    class DecodedSound {
        -CircularBuffer _soundBuffer;
    }

    class ISoundManager {
        +int recordAudio() = 0;
        +int playAudio() = 0;
        +bool isStreamActive() = 0;
        +bool isMicMuted() = 0;
        +bool isOutputMuted() = 0;
        +DecodedSound getSound() const = 0;
    }

    class IEncodeManager {
        +EncodedSound encode(DecodedSound &sound) = 0;
        +DecodedSound decode(EncodedSound &sound) = 0;
    }
}

namespace SoundLib {
    class PortAudioManager {
        +void recordCallback();
        +void playCallback();
        -std::shared_ptr<DecodedSound> _sound;
        -PaStream *_stream;
        -PaStreamParameters _outputParameters;
        -PaStreamParameters _inputParameters;
    }

    class OpusEncoderManager {
        -OpusEncoder *_encoder;
        -OpusDecoder *_decoder;
    }
}

'Sound.ISoundManager->Sound.ASoundManager
Sound.ISoundManager->SoundLib.PortAudioManager
Sound.IEncodeManager->SoundLib.OpusEncoderManager
@enduml