@startuml Babel
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

namespace Client {

namespace GUI {
    namespace pages {
        class RegisterWindow extends Qwidget
        {

        }

        class LoginWindow extends Qwidget
        {

        }

        class ProfilWindow extends Qwidget
        {

        }
    }

    class AppManager
    {
        +std::vector<Qwidget> _pages;
        +void setCurrentPage();
    }

    class BabelManager
    {
    }

    class CommandFactory
    {

    }

}

namespace Audio {

}

namespace Network {

}

namespace Exceptions {

class ClientException extends std::exception
{
    +const char *what() const noexcept override;
}

class CommandError extends ClientException
{

}

class CommandError
{

}

}



}


@enduml